Metaswitch/astaire

- src/Makefile
- src/main.cpp
You missed my duck, admittedly I distracted you by initializing the term_sem in the exception handler, but, had you looked closer, you'd have seen that a few lines later I called a function on an uninitialized variable.  Good thing astaire never crashes :worried:.
> Reviewer Alex - Remove ExceptionHandler reference

- debian/astaire.init.d
- include/astaire_statistics.hpp
- include/memcached_tap_client.hpp
- src/astaire.cpp
- src/astaire_statistics.cpp
- src/main.cpp
- src/memcached_tap_client.cpp
Andy,
Please can you review my live test fixes to Astaire?  This includes the following
*   running Astaire "nice-d" to ensure it never steals CPU from Sprout
*   waiting for 2s at the start of a "wait-sync" to ensure it doesn't think the process is already completed when actually it hasn't started yet
*   outputting the number of entries resynchronized as well as the ratio of buckets when reporting progress
*   fixing statistics to not report thousands of times a second and kill snmpd
*   initialize per-connection statistics' `timestamp_us` field correctly
*   setting the syslog process name correctly - I also need to fix this elsewhere, and that's tracked by https://github.com/Metaswitch/sprout/issues/973
*   doing a Get and Add or Replace rather than just an Add to close the window …
> [Reviewer: Andy] Miscellaneous live-test fixes

- debian/astaire.init.d
- include/astaire.hpp
- include/astaire_pd_definitions.hpp
- include/memcached_tap_client.hpp
- src/astaire.cpp
Please can you review this PR to enhance Astaire to pro-actively restore redundancy when a memcached server restarts. This also fixes some edge cases where data could be lost on a scaling operation if one of the current servers had recently restarted. 
The code should match the design we discussed. Specifically I have:
* Refactored the code to use a new "control thread" that periodically polls the local memcached server to see if it has restarted, and can also be kicked by the signal handlers.
* Changed the work-list processing so that Astaire streams vbuckets from all replicas, not just one of them. The resync is only considered as failed if a vbucket could not be streamed from any replica. 
* Added code to tag (and un-tag) the memcached server as being up-to-date. 
* Modified the ENT …
> [Reviewer: Andy] Proactively restore memcached redundancy

- src/astaire.cpp
Spotted a bug where if you have a single memcached cluster and memcached restarts, Astaire will get into a loop where it:
1. Spots its tag is missing and a resync is required. 
2. Calculates the worklist and realises there is nothing to do. It does not add its tag at this point.
3. Goto 1
Fixed by making Astaire tag memcached whenever it starts a resync, not just when it processes a worklist.
@bossmc has reviewed
> Prevent tight loop if memcached restarts and there is no work to do

- debian/astaire.init.d
- debian/astaire.install
As discussed. I think my testing of Chronos scaling through Chef will test that Astaire still works as a side-effect - I'm not planning to do any separate testing.
> [Reviewer: Ellie] Put cw_stat in its own directory to avoid clashing with Chronos

- src/astaire.cpp
Andy please can you review this PR that fixes #11. 
Tested by spinning up an AIO node and checking (using syslog) that Astaire did not do a resync in any of the following scenarios:
* Memcached restarted
* Astaire restarted
* `sudo service astaire reload`
* `sudo service astaire full-resync`
> [Reviewer: Andy] Only add a vbucket to the worklist if there are replicas to stream it from

- debian/rules
This PR fixes #14 by making dpkg not start astaire. The options are the same as passed to sprout. 
Tested by upgrading astaire to a version with the fix and checking that it did not crash over the upgrade.
> [Reviewer: Andy] Tell dpkg not to start astaire

- debian/astaire.postinst
- debian/astaire.prerm
- debian/control
- include/memcached_tap_client.hpp
- root/etc/init/astaire-throttle.conf
- src/memcached_tap_client.cpp
This PR contains the following fixes:
* Add an `astaire-throttle` service that limits astaire's CPU usage with `cpulimit`.
* Make the connection object use a bigger read buffer (to reduce the number of read calls we need to make). This gives a small perf improvement. 
* Fix The opcode for the `ReplaceReq` object.
All tested as part of my astaire stress testing. I've also done some more functional testing of the astaire-throttle service:
* Upgrade astaire to a version containing the service. It was started automatically. 
* Reboot the machine. Service is started automatically. 
* Kicked off a full resync by killing memcached. Top showed astaire was limited to the correct ammount of CPU. 
* Change the config option and restart the service. `ps` showed the change had been picked up. 
I will …
> [Reviewer: Andy] Astaire stress test fixes

- debian/astaire.init.d
Added setting of namespace_prefix to support multiple networks.
> Set namespace prefix for multiple network support (fixed issue #19)

- Makefile
- src/Makefile
In order to avoid confusion when "make test" refuses to build.
Deliberately commented out rather than deleted in order to make obvious that its omission is intentional.
> Reviewer AMC: Remove unsupported test targets from Makefile

- include/memcached_tap_client.hpp
- src/memcached_tap_client.cpp
- src/proxy_server.cpp
Rob, please could you review this PR that adds GETK support to astaire. This is the same as a GET command except that you have to put the requested key on the response. This will be needed to interop with `MemcachedStore` as libmemcached only uses GETKs.
Tested with pylibmc (which is a wrapper on top of libmemcached, so uses GETKs as well).
> [Reviewer: Rob] Implement GETKs as these are used by libmemcached

- include/memcached_backend.hpp
- src/memcached_backend.cpp
- src/memcached_tap_client.cpp
A few miscellaneous fixes:
* Failed GETs should not have any flags. 
* If a key does not exist, a REPLACE fails with ITEM_NOT_STORED. Deletes can fail if the key does not exist (in the memcache protocol at least). Pass these return codes back to the user of astaire. 
Tested with dalli (a ruby memcahed client).
> [Reviewer: Rob] Misc fixes from live testing

- include/proxy_server.hpp
- src/main.cpp
- src/proxy_server.cpp
Great fun to write, I love casting `struct sockaddr`s.
If Astaire gets passed `--bind-addr 127.0.0.2`, it should bind to just that address - if not, it should bind to the ANY address, as before.
I'll test this through clearwater-fv-test - both still listening on ANY by default, and that the specific address binding works. I might just do ad-hoc checking of that, though, rather than regressible checks.
> [Reviewer: Andy] Allow a command-line argument to bind to a specific address

- src/memcached_backend.cpp
As discussed, we disable Nagle in the memcached backend in Astaire as it buys us nothing and opens up various window conditions (that the FV tests hit). I've checked this works using the FV tests.
> [Review: Andy] Disable Nagle

- debian/astaire.postinst
- debian/astaire.triggers
Add alarm agent triggers - part of fix for https://github.com/Metaswitch/clearwater-snmp-handlers/issues/118
> [No reviewer] Add alarm triggers

- src/main.cpp
Rob. I dont think it really needs reviewed, but just to check: are you happy for me to merge the other 1 line changes as below into their respective dev branches? 
I will also be removing the 'clear_all' method, so that any locations i miss will kill the builds.
> [Reviewer: Rob] remove call to clear all alarms

- root/usr/share/clearwater/infrastructure/scripts/astaire.monit
Use check-uptime to clear alarms and avoid suprious monit failures.
> [Reviewer: None] Use updated check-uptime script.

- include/memcached_backend.hpp
- src/astaire.cpp
- src/memcached_backend.cpp
This PR has the update to the vBucket alarm, to make it check if 30 seconds have passed since the last alarm update before re-sending alarm status. 
It also includes a line to explicitly clear the Astaire re-sync alarm.
(Commits made before comments on capitalisation :P)
> [Reviewer: Rob] vBucket alarm modifications

- root/usr/share/clearwater/infrastructure/scripts/check-astaire-uptime
Monit can't pass arguments to check-program scripts in its current
version.
> [Reviewer: None] Cope with Monit restrictions

- debian/astaire.init.d
This is a change to the wait-sync command (see similar PR linked to this one from the chronos repo) to limit the time spent in a wait-sync loop if nothing is happening (i.e. the bucket count isn't changing).  This means that any operations blocked on the wait (such as scale in/out operations) are not blocked indefinitely due to, say, a failure of one of the remote nodes (which you cause the bucket count to eventually stick at a non-zero value).
A syslog message is written to indicate that the count is stuck.
Tested by running explicit wait-sync commands having hacked the script not to exit when the count reaches zero.
> [Reviewer EM] Cap sync waits at 10 minutes so that scaling can complete

- include/memcached_tap_client.hpp
- src/proxy_server.cpp
Fixed issue #72 
Just make a DEBUG log to suppress the warning. By setting keep_going false, we'll delete the connection anyway, so the only change is to the logging.
Testing:
- live tested (you need a split-clusters style sprout to connect to Astaire as a memcached proxy, and then quiescing the sprout will send a QUIT command)
> [Reviewer: Ellie] Suppress error log on memcached QUIT command

- debian/astaire.postinst
This matches what we do elsewhere (restarting clearwater-infrastructure), and resolves problems
with config not being available.
We use invoke-rc.d as we are in a post-install script, and this checks policy regarding what services shoudl be started, which allows us to prevent services being started using policy.
> [Reviewer: Seb] Install monit script by restarting infrastructure

- include/memcached_backend.hpp
- src/Makefile
- src/memcached_backend.cpp
Should drastically reduce the number of connections astaire needs to memcached. Previously, each thread maintained a connection to every memcached it talked to for it's entire lifetime. Now each thread asks for a connection from the connection pool only when it needs it, and returns it to the pool when it's done.
Tested in clearwater-fv-test and live.
> [Reviewer: AJH] Add memcached connection pooling to Astaire

- src/Makefile
Seb,
Simple fix - https://github.com/Metaswitch/cpp-common/pull/680 adds a requirement on linking to boost_regex.
> [Reviewer: Seb] Fix Boost Regex Linker Error

- src/proxy_server.cpp
Astaire's current logs log the port number using network byte ordering, not host byte ordering.
This means the number given is wrong.
This fixes that.
> [Reviewer: Seb] Log ports in the correct fashion

- src/proxy_server.cpp
I spotted that if Astaire was unable to contact any memcached processes while load was running through the system, Astaire's memory usage started rising continuously and didn't fall back down once memcached was restarted.
After some digging, it turned out that Astaire creates its proxy threads in state `joinable`. When a thread is created in this state, the system won't clear up the thread resources until `join()` is called on the thread, even if the thread has already terminated.
We never call `join()` on these threads, as they're just created to handle a single connection and then left to terminate once that connection is closed.
This means that we were leaking memory with every thread that terminated. Under mainline operation, we expect that these threads will persist for a while …
> [Reviewer: Adam] Astaire memory leak

- include/memcached_tap_client.hpp
- src/memcached_tap_client.cpp
See description in https://github.com/Metaswitch/cpp-common/pull/703.
Like it says.   Astaire doesn't have any UTs, but I've tested live.   
We don't think there are ever legitimate use cases where we need to store more than 64k of data, but there are currently cases where we will try to store more than this -- e.g. IMPI data can grow arbitrarily large if a sub sends in lots of rapid REGISTERs that get challenged.
I thought about enforcing a request size limit in Astaire, but since there is no such limit in memcached this didn't feel right.   Instead I've added a limit on the client side (memcachedstore).   See https://github.com/Metaswitch/cpp-common/pull/703
> Don't overflow on large messages

- src/memcached_backend.cpp
This, along with (https://github.com/Metaswitch/cpp-common/pull/709) fixes issue: https://github.com/Metaswitch/clearwater-issues/issues/2681.  See the final comment there for an explanation of the fix.
Tested live with sipp stress (80 REGISTERs per second) running against AWS deployment whilst network connectivity is periodically dropped to one Vellum node.
> Fix memcached timeouts

- src/memcached_backend.cpp
See also https://github.com/Metaswitch/cpp-common/pull/713.
Addresses Seb's feedback on https://github.com/Metaswitch/cpp-common/pull/709#pullrequestreview-75763226 and https://github.com/Metaswitch/astaire/pull/99.
Most significantly the CONNECT-TIMEOUT configured in the memcachedstore / memcached_backend is actually always overridden by the one configured in the MemcachedConnectionPool which is confusing.   Get rid of it and comment appropriately.
> Remove confusing duplicate configuration of memcached connect timeout

- src/memcached_backend.cpp
Adds additional error logs to say which IP addresses the failing memcached where from with read or write. I have run the live tests in Clearwater-fv-test but have done no live testing.
> Add more error logs to failing to read or write data
